development:
  adapter:  postgresql
  host:     localhost
  port:     5432
  encoding: unicode
  database: CompanyLibrary_dev
  pool:     5
  username: postgres
  password: postgres
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  port:     5432
  encoding: unicode
  database: CompanyLibrary_test
  pool:     5
  username: postgres
  password: postgres
  template: template0

production:
  adapter:  <%= ENV['COMPANYLIBRARY_PROD_ADAPTER'] %>
  host:     <%= ENV['COMPANYLIBRARY_PROD_HOST'] %>
  port:     <%= ENV['COMPANYLIBRARY_PROD_PORT'] %>
  encoding: unicode
  database: <%= ENV['COMPANYLIBRARY_PROD_DATABASE'] %>
  pool:     5
  username: <%= ENV['COMPANYLIBRARY_PROD_USER'] %>
  password: <%= ENV['COMPANYLIBRARY_PROD_PASS'] %>
  template: template0